package org.khasanof.migration.domain;

import org.khasanof.migration.domain.common.OrganizationMicroservice;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizationMicroserviceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMicroserviceAllPropertiesEquals(
        OrganizationMicroservice expected,
        OrganizationMicroservice actual
    ) {
        assertOrganizationMicroserviceAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizationMicroserviceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMicroserviceAllUpdatablePropertiesEquals(
        OrganizationMicroservice expected,
        OrganizationMicroservice actual
    ) {
        assertOrganizationMicroserviceUpdatableFieldsEquals(expected, actual);
        assertOrganizationMicroserviceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMicroserviceAutoGeneratedPropertiesEquals(
        OrganizationMicroservice expected,
        OrganizationMicroservice actual
    ) {
        assertThat(expected)
            .as("Verify OrganizationMicroservice auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMicroserviceUpdatableFieldsEquals(
        OrganizationMicroservice expected,
        OrganizationMicroservice actual
    ) {
        assertThat(expected)
            .as("Verify OrganizationMicroservice relevant properties")
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()))
            .satisfies(e -> assertThat(e.getUpdated()).as("check updated").isEqualTo(actual.getUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationMicroserviceUpdatableRelationshipsEquals(
        OrganizationMicroservice expected,
        OrganizationMicroservice actual
    ) {
        assertThat(expected)
            .as("Verify OrganizationMicroservice relationships")
            .satisfies(e -> assertThat(e.getMicroservice()).as("check microservice").isEqualTo(actual.getMicroservice()))
            .satisfies(e -> assertThat(e.getOrganization()).as("check organization").isEqualTo(actual.getOrganization()));
    }
}
